using System;

namespace Twinsanity.TwinsanityInterchange.Enumerations
{
    public static class Enums
    {
        public enum Layouts
        {
            LAYER_1,
            LAYER_2,
            LAYER_3,
            LAYER_4,
            LAYER_5,
            LAYER_6,
            LAYER_7,
            LAYER_8
        }

        public enum ObjectType
        {
            PLAYABLE_CHARACTER,
            PICKUP,
            CRATE,
            CREATURE,
            GENERIC_OBJECT,
            GRABBABLE,
            PAY_GATE,
            GRAPLE,
            PROJECTILE
        }

        public enum LodType
        {
            FULL = 0x1001,
            COMPRESSED = 0x1002
        }

        [Flags]
        public enum InstanceState : UInt32
        {
            Deactivated = 1 << 0,
            CollisionActive = 1 << 1,
            Visible = 1 << 2,
            ShadowActive = 1 << 3,
            PlayableCharacterCanMoveAlong = 1 << 4,
            Unknown1 = 1 << 5,
            SyncCrossChunkState = 1 << 6,
            Unknown2 = 1 << 7,
            ReceiveOnTriggerSignals = 1 << 8,
            CanDamageCharacter = 1 << 9,
            SolidToBodySlam = 1 << 10,
            SolidToSlide = 1 << 11,
            SolidToSpin = 1 << 12,
            SolidToTwinSlam = 1 << 13,
            SolidToThrownCortex = 1 << 14,
            Targettable = 1 << 15,
            CanAlwaysDamageCharacter = 1 << 16,
            BulletsWillBounceBack = 1 << 17,
            Unknown3 = 1 << 18,
            Unknown4 = 1 << 19,
            Unknown5 = 1 << 20,
            Unknown6 = 1 << 21,
            Unknown7 = 1 << 22,
            Unknown8 = 1 << 23,
            Unknown9 = 1 << 24,
            Unknown10 = 1 << 25,
            Unknown11 = 1 << 26,
            Unknown12 = 1 << 27,
            Unknown13 = 1 << 28,
            Unknown14 = 1 << 29,
            Unknown15 = 1 << 30,
            Unknown16 = 1U << 31,
        }

        [Flags]
        public enum TriggerActivatorObjects
        {
            PlayableCharacter = 1 << 0,
            Pickups = 1 << 1,
            Crates = 1 << 2,
            Creatures = 1 << 3,
            GenericObjects = 1 << 4,
            Grabbables = 1 << 5,
            PayGates = 1 << 6,
            Graples = 1 << 7,
            Projectiles = 1 << 8
        }

        [Flags]
        public enum AppliedShaders : UInt64
        {
            LitSkinnedModel = 0x2,
            StandardLit = 0x4,
            StandardUnlit = 0x8,
            UnlitBillboard = StandardUnlit,
            UnlitSkydome = 0x10,
            ColorOnly = 0x20,
            LitEnvironmentMap = 0x40,
            LitMetallic = 0x200,
            LitReflectionSurface = 0x400,
            Particle = 0x1000,
            Decal = 0x2000,
            UnlitGlossy = 0x4000,
            UnlitEnvironmentMap = 0x8000,
            UnlitClothDeformation = 0x10000,
            UnlitClothDeformation2 = 0x80000,
            UiShader = 0x10000000,
        }

        [Flags]
        public enum SurfaceCollisionFlags : UInt32
        {
            Unknown1 = 1 << 0,
            Unknown2 = 1 << 1,
            Unknown3 = 1 << 2,
            Unknown4 = 1 << 3,
            Unknown5 = 1 << 4,
            Unknown6 = 1 << 5,
            Unknown7 = 1 << 6,
            Unknown8 = 1 << 7,
            Unknown9 = 1 << 8,
            Unknown10 = 1 << 9,
            Unknown11 = 1 << 10,
            Unknown12 = 1 << 11,
            Unknown13 = 1 << 12,
            Unknown14 = 1 << 13,
            Unknown15 = 1 << 14,
            Unknown16 = 1 << 15,
            Unknown17 = 1 << 16,
            Unknown18 = 1 << 17,
            Unknown19 = 1 << 18,
            Unknown20 = 1 << 19,
            Unknown21 = 1 << 20,
            Unknown22 = 1 << 21,
            Unknown23 = 1 << 22,
            Unknown24 = 1 << 23,
            Unknown25 = 1 << 24,
            Unknown26 = 1 << 25,
            Unknown27 = 1 << 26,
            Unknown28 = 1 << 27,
            Unknown29 = 1 << 28,
            Unknown30 = 1 << 29,
            Unknown31 = 1 << 30,
            Unknown32 = 1U << 31,
        }

        public enum SurfaceType : UInt16
        {
            SURF_DEFAULT = 0,
            SURF_GENERIC_SLIGHTLY_SLIPPY = 1,
            SURF_GENERIC_MEDIUM_SLIPPY = 2,
            SURF_LAVA = 3,
            SURF_GENERIC_INSTANT_DEATH = 4,
            SURF_FALL_THRU_DEATH = 5,
            SURF_NORMAL_GRASS = 6,
            SURF_SLIPPY_METAL = 7,
            SURF_NORMAL_WOOD = 8,
            SURF_NORMAL_METAL = 9,
            SURF_NORMAL_SAND = 10,
            SURF_NORMAL_MUD = 11,
            SURF_NORMAL_WATER = 12,
            SURF_NORMAL_ROCK = 13,
            SURF_SLIPPY_ROCK = 14,
            SURF_NORMAL_SNOW = 15,
            SURF_STICKY_SNOW = 16,
            SURF_ICE = 17,
            SURF_GLASS_WALL = 18,
            SURF_HACK_RAIL = 19,
            SURF_CAMERA_BLOCKING = 20,
            SURF_NORMAL_STONE_TILES = 21,
            SURF_ICE_LOW_SLIPPY = 22,
            SURF_DROWNING_PLANE = 23,
            SURF_BLOCK_PLAYER = 24,
            SURF_GENERIC_MEDIUM_SLIPPY_RIGID_ONLY = 25,
            SURF_NONSOLID_ELECTRIC_DEATH = 26,
            SURF_BLOCK_AI_ONLY = 27,
            // After this custom surfaces start. Game supports a hard limit of 128 collision surfaces
            SURF_CUSTOM_1 = 28,
            SURF_CUSTOM_2,
            SURF_CUSTOM_3,
            SURF_CUSTOM_4,
            SURF_CUSTOM_5,
            SURF_CUSTOM_6,
            SURF_CUSTOM_7,
            SURF_CUSTOM_8,
            SURF_CUSTOM_9,
            SURF_CUSTOM_10,
            SURF_CUSTOM_11,
            SURF_CUSTOM_12,
            SURF_CUSTOM_13,
            SURF_CUSTOM_14,
            SURF_CUSTOM_15,
            SURF_CUSTOM_16,
            SURF_CUSTOM_17,
            SURF_CUSTOM_18,
            SURF_CUSTOM_19,
            SURF_CUSTOM_20,
            SURF_CUSTOM_21,
            SURF_CUSTOM_22,
            SURF_CUSTOM_23,
            SURF_CUSTOM_24,
            SURF_CUSTOM_25,
            SURF_CUSTOM_26,
            SURF_CUSTOM_27,
            SURF_CUSTOM_28,
            SURF_CUSTOM_29,
            SURF_CUSTOM_30,
            SURF_CUSTOM_31,
            SURF_CUSTOM_32,
            SURF_CUSTOM_33,
            SURF_CUSTOM_34,
            SURF_CUSTOM_35,
            SURF_CUSTOM_36,
            SURF_CUSTOM_37,
            SURF_CUSTOM_38,
            SURF_CUSTOM_39,
            SURF_CUSTOM_40,
            SURF_CUSTOM_41,
            SURF_CUSTOM_42,
            SURF_CUSTOM_43,
            SURF_CUSTOM_44,
            SURF_CUSTOM_45,
            SURF_CUSTOM_46,
            SURF_CUSTOM_47,
            SURF_CUSTOM_48,
            SURF_CUSTOM_49,
            SURF_CUSTOM_50,
            SURF_CUSTOM_51,
            SURF_CUSTOM_52,
            SURF_CUSTOM_53,
            SURF_CUSTOM_54,
            SURF_CUSTOM_55,
            SURF_CUSTOM_56,
            SURF_CUSTOM_57,
            SURF_CUSTOM_58,
            SURF_CUSTOM_59,
            SURF_CUSTOM_60,
            SURF_CUSTOM_61,
            SURF_CUSTOM_62,
            SURF_CUSTOM_63,
            SURF_CUSTOM_64,
            SURF_CUSTOM_65,
            SURF_CUSTOM_66,
            SURF_CUSTOM_67,
            SURF_CUSTOM_68,
            SURF_CUSTOM_69,
            SURF_CUSTOM_70,
            SURF_CUSTOM_71,
            SURF_CUSTOM_72,
            SURF_CUSTOM_73,
            SURF_CUSTOM_74,
            SURF_CUSTOM_75,
            SURF_CUSTOM_76,
            SURF_CUSTOM_77,
            SURF_CUSTOM_78,
            SURF_CUSTOM_79,
            SURF_CUSTOM_80,
            SURF_CUSTOM_81,
            SURF_CUSTOM_82,
            SURF_CUSTOM_83,
            SURF_CUSTOM_84,
            SURF_CUSTOM_85,
            SURF_CUSTOM_86,
            SURF_CUSTOM_87,
            SURF_CUSTOM_88,
            SURF_CUSTOM_89,
            SURF_CUSTOM_90,
            SURF_CUSTOM_91,
            SURF_CUSTOM_92,
            SURF_CUSTOM_93,
            SURF_CUSTOM_94,
            SURF_CUSTOM_95,
            SURF_CUSTOM_96,
            SURF_CUSTOM_97,
            SURF_CUSTOM_98,
            SURF_CUSTOM_99,
            SURF_CUSTOM_100,
        }
    }
}
