<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Images/tt_lab_logo_v6_2k.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
        <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsWindows)'=='true'">
        <DefineConstants>_WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(IsLinux)'=='true'">
        <DefineConstants>_LINUX</DefineConstants>
    </PropertyGroup>
    
    <PropertyGroup>
        <BuildDependsOn>
            $(BuildDependsOn);CopyNativeLibs
        </BuildDependsOn>
    </PropertyGroup>
    
    <Target Name="CopyNativeLibs" AfterTargets="AfterBuild">
        <ItemGroup>
            <NativeLibrariesWindows Include="$(MSBuildProjectDirectory)\Libraries\Native\Windows\*.dll"/>
            <RuntimeCopyPathWindows Include="$(MSBuildProjectDirectory)\$(OutputPath)\runtimes\win-x64\native\"/>
        </ItemGroup>
        <ItemGroup>
            <NativeLibrariesLinux Include="$(MSBuildProjectDirectory)\Libraries\Native\Linux\*.so"/>
            <RuntimeCopyPathLinux Include="$(MSBuildProjectDirectory)\$(OutputPath)\runtimes\linux-x64\native\"/>
        </ItemGroup>
        
        <Message Text="Copying Windows native libraries into resulting executable..." Importance="high"/>
        <Copy SourceFiles="@(NativeLibrariesWindows)" DestinationFolder="@(RuntimeCopyPathWindows)"/>
        <Message Text="Copying Linux native libraries into resulting executable..." Importance="high"/>
        <Copy SourceFiles="@(NativeLibrariesLinux)" DestinationFolder="@(RuntimeCopyPathLinux)"/>
    </Target>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12" />
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
        <PackageReference Include="Avalonia.Labs.Gif" Version="11.3.1" />
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.12" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="AvaloniaEdit.TextMate" Version="11.3.0" />
        <PackageReference Include="Caliburn.Micro.Avalonia" Version="5.0.258-beta" />
        <PackageReference Include="Caliburn.Micro.Platform.Core" Version="5.0.181-beta" />
        <PackageReference Include="Classic.Avalonia.Theme" Version="11.3.0.3" />
        <PackageReference Include="Dock.Avalonia" Version="11.3.11.16" />
        <PackageReference Include="Dock.Avalonia.Themes.Simple" Version="11.3.11.16" />
        <PackageReference Include="Dock.Model.Avalonia" Version="11.3.11.16" />
        <PackageReference Include="Dock.Model.ReactiveUI" Version="11.3.11.16" />
        <PackageReference Include="Dock.Model.ReactiveUI.Services" Version="11.3.11.16" />
        <PackageReference Include="Dock.Serializer.Newtonsoft" Version="11.3.11.16" />
        <PackageReference Include="geometry3Sharp" Version="1.0.324" />
        <PackageReference Include="GlmSharpStd" Version="0.9.8" />
        <PackageReference Include="Meshoptimizer.NET" Version="1.0.7" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="ProDataGrid" Version="11.3.11-preview.19" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
        <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.5.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ReactiveUI.Validation" Version="6.0.18" />
        <PackageReference Include="SharpGLTF.Core" Version="1.0.6" />
        <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
        <PackageReference Include="SharpHash" Version="1.2.0" />
        <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.23.0" />
        <PackageReference Include="SoundFlow" Version="1.4.0">
            <ExcludeAssets>content; contentFiles; STATEMENT.md</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Splat" Version="18.1.1" />
        <PackageReference Include="Splat.Builder" Version="18.1.1" />
        <PackageReference Include="Splat.Core" Version="18.1.1" />
        <PackageReference Include="Splat.DependencyInjection.SourceGenerator" Version="1.2.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Splat.Logging" Version="18.1.1" />
        <PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="18.1.1" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" Version="11.3.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TwinTech\TwinTech.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Images/AfroGod.png"/>
      <AvaloniaResource Include="Images/God_Messenger.png"/>
      <AvaloniaResource Include="Images/SadTransparent.gif"/>
      <AvaloniaResource Include="Images/tt_lab_logo_v6_2k.ico" />
      <Content Include="Images\SadTransparent.gif">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Media\**\*">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="BlenderTools\dist\*">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Libraries\Native\Windows\PS2ImageMaker.dll">
          <PackagePath>runtimes/win-x64/native</PackagePath>
      </Content>
      <Content Include="Libraries\Native\Windows\meshoptimizer.dll">
          <PackagePath>runtimes/win-x64/native</PackagePath>
      </Content>
      <Content Include="Libraries\Native\Linux\libPS2ImageMaker.so">
          <PackagePath>runtimes/linux-x64/native</PackagePath>
      </Content>
      <Content Include="Libraries\Native\Linux\libmeshoptimizer.so">
          <PackagePath>runtimes/linux-x64/native</PackagePath>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Libraries\Native\Linux\" />
    </ItemGroup>
</Project>
