<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Images/tt_lab_logo_v6_2k.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
        <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsWindows)'=='true'">
        <DefineConstants>_WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(IsLinux)'=='true'">
        <DefineConstants>_LINUX</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.10"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.10"/>
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.3.10" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Caliburn.Micro.Avalonia" Version="5.0.258-beta" />
        <PackageReference Include="Caliburn.Micro.Platform.Core" Version="5.0.181-beta" />
        <PackageReference Include="Classic.Avalonia.Theme" Version="11.3.0.3" />
        <PackageReference Include="geometry3Sharp" Version="1.0.324" />
        <PackageReference Include="GlmSharpStd" Version="0.9.8" />
        <PackageReference Include="Meshoptimizer.NET" Version="1.0.7" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
        <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.5.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SharpGLTF.Core" Version="1.0.6" />
        <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
        <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.22.0" />
        <PackageReference Include="SoundFlow" Version="1.3.0" />
        <PackageReference Include="Splat" Version="18.1.1" />
        <PackageReference Include="Splat.Builder" Version="18.1.1" />
        <PackageReference Include="Splat.Core" Version="18.1.1" />
        <PackageReference Include="Splat.DependencyInjection.SourceGenerator" Version="1.2.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Splat.Logging" Version="18.1.1" />
        <PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="18.1.1" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" Version="11.3.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TwinTech\TwinTech.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Images\AfroGod.png"/>
      <AvaloniaResource Include="Images\God_Messenger.png"/>
      <AvaloniaResource Include="Images\SadTransparent.gif"/>
      <AvaloniaResource Include="Images\tt_lab_logo_v6_2k.ico" />
      <Content Include="Media\**\*">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="BlenderTools\dist\*">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>  
    </ItemGroup>
</Project>
